version: '3'
services:
  frontend:
    build: 
      context: frontend/.
    ports:
      - "8091:8091"
  database:
    image: postgres
    container_name: diwy-postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: 
      context: .
    container_name: diwy-backend
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8011:8011"
    command: uvicorn web_app.run:app --host=0.0.0.0 --port=8011
  bot:
    build: 
      context: .
    container_name: diwy-bot
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: python3 bot.py
